### ISSUE TITLE
Firen cant change running direction

### ISSUE THREAD

**Issue by DaKnig** [Project-F/F.LF#12]
when trying to manipulate Firen's running path in his "Blaze" attack up or down, creates fire entities traveling the direction you choose but Firen just runs in a straight line.

expected behavior: Firen moves up or down

actual behavior: Firen runs in a completely straight line

**Comment by mcwissink** [comment]
Seems like Firen's state 19 isn't implemented. The moving fire problem is less obvious to me.

**Comment by mcwissink** [comment]
Apparently all objects inherit a vertical velocity based on the parents vertical direction. The ground flames that has a vertical velocity has Firen as a parent. Those ground flames also spawn an neighboring ground flame, but since the parent ground flames don't have a vertical direction, their children remain stationary. Not really sure how to appropriately fix this issue.

**Comment by DaKnig** [comment]
besides some bugs, in lf2 the ground flames should never be moving . unless we are going for a bug-to-bug reimplementation , we should just make em stationary in my opinion - if they inherit the velocity, it should be nullified in the constructor of the ground flames- just `velocity = 0` or whatever is the equivalent or maybe make the attack that generates them create them with 0 velocity. sorry but I don't understand the code so can't help there...

**Comment by tyt2y3** [comment]
Thank you so much everyone for the details! I am intrigued by the sudden interest in this project. Even I had forgotten all the implementation details. That say, I might be able to mentor a enthusiast who are interested in getting involved.

**Comment by tyt2y3** [comment]
Thank you @mcwissink !
